- name: Update APT Cache
  apt:
    update_cache: yes

- name: Install prerequisites
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - gnupg
    - ca-certificates
    - apt-transport-https
    - software-properties-common

- name: Install Node.js (LTS version)
  apt:
    name: nodejs
    state: present

- name: Install PM2 globally
  npm:
    name: pm2
    global: yes

- name: Import MongoDB public GPG key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-6.0.asc
    state: present

- name: Add MongoDB repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse
    state: present
    filename: mongodb-org

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: true

- name: Start and enable MongoDB
  systemd:
    name: mongod
    enabled: yes
    state: started

- 


