[frontend]
frontend

[backend]
backend

; actual command in file "nano ~/.ssh/config" -> nano ~/.ssh/config
; # Bastion host (Frontend EC2 in public subnet)
; Host frontend
;   HostName 51.21.247.121         # Frontend EC2 public IP
;   User ubuntu
;   IdentityFile ~/path/to/terraform/deployer-key.pem

; # Backend host (Private EC2 in private subnet)
; Host backend
;   HostName 10.0.1.54             # Backend EC2 private IP
;   User ubuntu
;   IdentityFile ~/path/to/terraform/deployer-key.pem
;   ProxyJump frontend
